<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<script type="Text/javascript">
//=============================1、promise链式写法========================
    var p= new Promise((resolve,reject)=>{
        setTimeout(() => {
            resolve("成功");   
        }, 1000);
    });

    p.then(value=>{
        return new Promise((resolve,reject)=>{
            resolve("success");
        })
    }).then(value => {
        console.log(value);             
    }).then(value=>{
        console.log(value);             //返回成功状态，值因为上一个返回的promise对象的返回值为undefined，所以拿到的value为undefined
    }).catch(reason=>{                  //链式写法可在最后 进行一个失败的回调。then和catch都行。 称作：异常穿透。
        console.warn(reason);
    })

//============================= 2、promise异常穿透 ========================
var p1= new Promise((resolve,reject)=>{
        setTimeout(() => {
            resolve("成功");   
        }, 1000);
    });

    p1.then(value=>{
        return new Promise((resolve,reject)=>{
            resolve("success");
        })
    }).then(value => {
        throw "失败了!";                 //此处错误，在最后使用catch方法回调来处理的。
    }).then(value=>{
        console.log(value);             
    }).catch(reason=>{                  //链式写法可在最后 进行一个失败的回调。then和catch都行。 称作：异常穿透。
        console.warn(reason);
    })

//============================= 3、中断promise链 ========================
/* 常用的返回false，抛出错误没作用 
有且只有一种方式：返回一个Pending状态的promise对象  return new Promise(()=>{});
*/
var p1= new Promise((resolve,reject)=>{
        setTimeout(() => {
            resolve("成功");   
        }, 1000);
    });

    p1.then(value=>{
        return new Promise((resolve,reject)=>{
            resolve("success");
        })
    }).then(value => {

        console.log("00000"); 
        //中断promise链
        return new Promise(()=>{});             //返回一个pending状态的promise对象。因为返回对象状态未改变，所以不会继续执行。

    }).then(value=>{
        console.log(1111);             
    }).then(value=>{
        console.log(2222)
    }).catch(reason=>{                  
        console.warn(reason);
    })

</script>
</body>
</html>